# La versión 3 es la más utilizada y la que se recomienda
version: '3'

# Configuración de los servidores que vamos a necesitar
services: 
 
  # mysql es el nombre que vamos a dar a este primer servidor
  # Será el nombre que tendremos que usar cuando nos refiramos a él
  mysql:
    build: mysql/
    #Uso build en vez de image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dwes
      MYSQL_PASSWORD: dwes
      MYSQL_DATABASE: dwes
      
      
  phpmyadmin:
    #conectamos con mysql
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    #variables de entorno
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root 

  apache:
    build: apache/
    ports:
      - 80:80
    volumes:
      - proyecto:/var/www/html/

  php:
    build: php/
    ports:
      - 9000:9000
    volumes:
      - proyecto:/var/www/html/ 

volumes: 
  proyecto: